/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BanDetail: typeof import('./src/components/BanDetail.vue')['default']
    BanListItem: typeof import('./src/components/BanListItem.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    PlayerProfile: typeof import('./src/components/PlayerProfile.vue')['default']
    PlayerSearch: typeof import('./src/components/PlayerSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
